-- -*- mode: sql; sql-product: postgres; -*-

CREATE TABLE station (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	timezone TEXT NOT NULL, 
	location TEXT, 
	frequency TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE program (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	host_name TEXT, 
	is_syndicated BOOLEAN, 
	station_id INTEGER, 
	is_canonical BOOLEAN, 
	cnl_program_id INTEGER, 
	program_uri TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(station_id) REFERENCES station (id), 
	FOREIGN KEY(cnl_program_id) REFERENCES program (id)
);

CREATE TABLE recording (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	label TEXT, 
	catalog_no TEXT, 
	release_date DATE, 
	archiv_uri TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE person (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	prefix TEXT, 
	first_name TEXT, 
	middle_name TEXT, 
	last_name TEXT, 
	suffix TEXT, 
	is_canonical BOOLEAN, 
	cnl_person_id INTEGER, 
	archiv_uri TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(cnl_person_id) REFERENCES person (id)
);

CREATE TABLE performer (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	role TEXT NOT NULL, 
	person_id INTEGER NOT NULL, 
	cnl_person_id INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (role, person_id), 
	FOREIGN KEY(person_id) REFERENCES person (id), 
	FOREIGN KEY(cnl_person_id) REFERENCES person (id)
);

CREATE TABLE ensemble (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	is_canonical BOOLEAN, 
	cnl_ensemble_id INTEGER, 
	archiv_uri TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(cnl_ensemble_id) REFERENCES ensemble (id)
);

CREATE TABLE piece (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	name TEXT NOT NULL, 
	piece_type TEXT, 
	piece_key TEXT, 
	catalog_no TEXT, 
	is_canonical BOOLEAN, 
	cnl_piece_id INTEGER, 
	archiv_uri TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(cnl_piece_id) REFERENCES piece (id)
);

CREATE TABLE play (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	station TEXT NOT NULL, 
	play_info JSONB NOT NULL, 
	play_date DATE NOT NULL, 
	play_start TIME WITHOUT TIME ZONE NOT NULL, 
	play_end TIME WITHOUT TIME ZONE, 
	play_dur INTERVAL, 
	station_id INTEGER, 
	program_id INTEGER, 
	composer_id INTEGER, 
	piece_id INTEGER, 
	artist_ids INTEGER[], 
	ensemble_ids INTEGER[], 
	conductor_id INTEGER, 
	soloist_ids INTEGER[], 
	recording_id INTEGER, 
	notes TEXT[], 
	start_time TIMESTAMP WITH TIME ZONE, 
	end_time TIMESTAMP WITH TIME ZONE, 
	duration INTERVAL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(station_id) REFERENCES station (id), 
	FOREIGN KEY(program_id) REFERENCES program (id), 
	FOREIGN KEY(composer_id) REFERENCES person (id), 
	FOREIGN KEY(piece_id) REFERENCES piece (id), 
	FOREIGN KEY(conductor_id) REFERENCES person (id), 
	FOREIGN KEY(recording_id) REFERENCES recording (id)
);
