---
default:
  stations:
    C24:
      sample_url:   'http://classical24.publicradio.org/listings/listings.php?year=2018&month=09&day=06'
      url_fmt:      'http://classical24.publicradio.org/listings/listings.php?<DATE_STR>'
      date_fmt:     'year=%Y&month=%m&day=%d'
      time_zone:    'America/Chicago'
      playlist_ext: 'html'

    KDFC:
      sample_url:   'https://www.kdfc.com/playlist/2018/09/07/'
      sample_url2:  'https://www.kdfc.com/playlist/2018/09/06/?_pjax=%23main'
      url_fmt:      'https://www.kdfc.com/playlist/<DATE_STR>/'
      http_headers: {'User-Agent': 'Mozilla/5.0'}
      date_fmt:     '%Y/%m/%d'
      time_zone:    'America/Los_Angeles'
      playlist_ext: 'html'

    KING:
      sample_url:   'https://www.king.org/music-schedule/?npDate=010118'
      url_fmt:      'https://www.king.org/music-schedule/?<DATE_STR>'
      date_fmt:     'npDate=%m%d%y'
      time_zone:    'America/Los_Angeles'
      playlist_ext: 'html'

    KUSC:
      sample_url:   'https://www.kusc.org/playlist/2018/09/05/'
      sample_url2:  'https://www.kusc.org/playlist/2018/09/05/?_pjax=%23main'
      url_fmt:      'https://www.kusc.org/playlist/<DATE_STR>/'
      http_headers: {'User-Agent': 'Mozilla/5.0'}
      date_fmt:     '%Y/%m/%d'
      time_zone:    'America/Los_Angeles'
      playlist_ext: 'html'

    WCRB:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53877c98e1c80a130decb6c8/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?<DATE_STR>&format=json'
      widgetkey:    '53877c98e1c80a130decb6c8'
      date_fmt:     'date=%Y-%m-%d'
      time_zone:    'America/New_York'
      playlist_ext: 'json'

    WDAV:
      sample_url:   'https://app.wdav.org/app-playlist/index.cfm?thisday=2017-09-05'
      url_fmt:      'https://app.wdav.org/app-playlist/index.cfm?<DATE_STR>'
      date_fmt:     'thisday=%Y-%m-%d'
      time_zone:    'America/New_York'
      playlist_ext: 'html'

    WETA:
      sample_url:   'https://weta.org/fm/playlists?playlist_date[value][date]=09/05/2018'
      url_fmt:      'https://weta.org/fm/playlists?playlist_date[value]<DATE_STR>'
      date_fmt:     '[date]=%m/%d/%Y'
      time_zone:    'America/New_York'
      playlist_ext: 'html'

    WFMT:
      sample_url:   'https://www.wfmt.com/schedule/?pldate=08/05/2018'
      url_fmt:      'https://www.wfmt.com/schedule/?<DATE_STR>'
      date_fmt:     'pldate=%m/%d/%Y'
      time_zone:    'America/Chicago'
      playlist_ext: 'html'

    WQXR:
      sample_url:   'https://www.wqxr.org/playlist-daily/2018/sep/06/?scheduleStation=wqxr'
      url_fmt:      'https://www.wqxr.org/playlist-daily/<DATE_STR>/?scheduleStation=wqxr'
      date_fmt:     '%Y/%b/%d'  # %b must be lowercased
      time_zone:    'America/New_York'
      playlist_ext: 'html'

    WWFM:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53a98e36e1c80647e855fc88/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?<DATE_STR>&format=json'
      widgetkey:    '53a98e36e1c80647e855fc88'
      date_fmt:     'date=%Y-%m-%d'
      time_zone:    'America/New_York'
      playlist_ext: 'json'
      playlist_min: 5000
