---
default:
  station_base:
    http_headers:   {'User-Agent': 'Mozilla/5.0'}
    fetch_interval: 2.0

  stations:
    C24:
      sample_url:   'http://classical24.publicradio.org/listings/listings.php?year=2018&month=09&day=06'
      url_fmt:      'http://classical24.publicradio.org/listings/listings.php?<DATE_STR>'
      date_fmt:     'year=%Y&month=%m&day=%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      parser_cls:   'ParserC24'
      synd_level:   100

    CPR:
      sample_url:   'http://playlist.cprnetwork.org/api/playlistCL/selectDate:MjAxOC0wOS0xMg=='
      url_fmt:      'http://playlist.cprnetwork.org/api/playlistCL/selectDate:<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      date_func:    'base64encode'
      timezone:     'America/Denver'
      playlist_ext: 'json'
      parser_cls:   'Parser'

    HPR:
      sample_url:   'https://www.houstonpublicmedia.org/classical/schedule/2018/09/12/'
      url_fmt:      'https://www.houstonpublicmedia.org/classical/schedule/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2013-05-01'
      parser_cls:   'Parser'

    IPR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/518277f7e1c83ecee40d8eb1/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '518277f7e1c83ecee40d8eb1'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'json'
      epoch:        '2013-07-01'
      parser_cls:   'ParserWWFM'
      synd_level:   90

    KDFC:
      sample_url:   'https://www.kdfc.com/playlist/2018/09/07/'
      sample_url2:  'https://www.kdfc.com/playlist/2018/09/06/?_pjax=%23main'
      url_fmt:      'https://www.kdfc.com/playlist/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2013-06-30'
      parser_cls:   'Parser'

    KING:
      sample_url:   'https://www.king.org/music-schedule/?npDate=01012018'
      url_fmt:      'https://www.king.org/music-schedule/?npDate=<DATE_STR>'
      date_fmt:     '%m%d%Y'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2014-01-01'
      parser_cls:   'Parser'

    KQAC:
      sample_url:   'https://daisy.allclassical.org/api/playlist/date/2018-09-12/'
      url_fmt:      'https://daisy.allclassical.org/api/playlist/date/<DATE_STR>/'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'json'
      epoch:        '2015-05-01'
      parser_cls:   'Parser'

    KUSC:
      sample_url:   'https://www.kusc.org/playlist/2018/09/05/'
      sample_url2:  'https://www.kusc.org/playlist/2018/09/05/?_pjax=%23main'
      url_fmt:      'https://www.kusc.org/playlist/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2013-01-06'
      parser_cls:   'Parser'

    MPR:
      sample_url:   'https://www.classicalmpr.org/playlist/classical-mpr/2018-09-12'
      url_fmt:      'https://www.classicalmpr.org/playlist/classical-mpr/<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      parser_cls:   'ParserMPR'
      synd_level:   80

    VPR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/518028fee1c810b152ff9766/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '518028fee1c810b152ff9766'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-12-15'
      parser_cls:   'ParserWWFM'
      synd_level:   50

    WBJC:
      sample_url:   'http://www.wbjc.com/2018/playlists/playlist-sep-15-18/'
      url_fmt:      'http://www.wbjc.com/2018/playlists/playlist-<DATE_STR>/'
      date_fmt:     '%b-%d-%y'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-01-01'
      parser_cls:   'Parser'

    WCPE:
      # Note: date in URL is the Monday of the week (needs to be handled in date_func)
      sample_url:   'https://theclassicalstation.org/music/archive/2018-09-17/tuesday.shtml'
      url_fmt:      'https://theclassicalstation.org/music/archive/<DATE_STR>.shtml'
      date_fmt:     '%Y-%m-%d/%A'
      date_func:    'wcpe_special'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2011-08-15'
      parser_cls:   'Parser'

    WCRB:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53877c98e1c80a130decb6c8/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53877c98e1c80a130decb6c8'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-07-01'
      parser_cls:   'ParserWWFM'
      synd_level:   30

    WDAV:
      sample_url:   'https://app.wdav.org/app-playlist/index.cfm?thisday=2017-09-05'
      url_fmt:      'https://app.wdav.org/app-playlist/index.cfm?thisday=<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      parser_cls:   'Parser'

    WETA:
      sample_url:   'https://weta.org/fm/playlists/2018-09-08'
      url_fmt:      'https://weta.org/fm/playlists/<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-01-01'
      parser_cls:   'Parser'

    WFMT:
      sample_url:   'https://www.wfmt.com/schedule/?pldate=08/05/2018'
      url_fmt:      'https://www.wfmt.com/schedule/?pldate=<DATE_STR>'
      date_fmt:     '%m/%d/%Y'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2018-07-01'
      parser_cls:   'Parser'

    WIAA:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/52615808e1c8fbf0ddcb3d04/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '52615808e1c8fbf0ddcb3d04'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-11-11'
      parser_cls:   'ParserWWFM'
      synd_level:   40

    WMHT:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51892578e1c81d34d1474a5d/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51892578e1c81d34d1474a5d'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-06-03'
      parser_cls:   'ParserWWFM'
      synd_level:   60

    WNED:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51929c5ce1c8c39684eeee82/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51929c5ce1c8c39684eeee82'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-12-24'
      parser_cls:   'ParserWWFM'
      synd_level:   20

    WQED:
      sample_url:   'https://www.wqed.org/fm/playlist?day=09/05/2018'
      url_fmt:      'https://www.wqed.org/fm/playlist?day=<DATE_STR>'
      date_fmt:     '%m/%d/%Y'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-07-10'
      parser_cls:   'Parser'

    WQXR:
      sample_url:   'https://www.wqxr.org/api/schedule_playlist_json/wqxr/2017/sep/01/'
      url_fmt:      'https://www.wqxr.org/api/schedule_playlist_json/wqxr/<DATE_STR>/'
      date_fmt:     '%Y/%b/%d'
      date_meth:    'lower'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      parser_cls:   'Parser'

    WRTI:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53c7dbe1e1c8b9c77b4b9b6e/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53c7dbe1e1c8b9c77b4b9b6e'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-05-01'
      parser_cls:   'ParserWWFM'
      synd_level:   10

    WWFM:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53a98e36e1c80647e855fc88/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53a98e36e1c80647e855fc88'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-11-11'
      playlist_min: 5000
      parser_cls:   'ParserWWFM'
      synd_level:   70

  refdata_base:
    http_headers:   {'User-Agent': 'Mozilla/5.0'}
    catdata_ext:   'html'
    fetch_interval: 2.0

  refdata:
    arkivmusic:
      # LATER: abstract to 'browse_by'
      url_fmt:      'http://www.arkivmusic.com/classical/NameList?alpha=<STARTS_WITH>&role_wanted=<ROLE>'

      categories:
        composers:
          role:     1
        performers:
          role:     2
        conductors:
          role:     3
        ensembles:
          role:     4

  database:
    local_dev:
      connect_str:  'postgresql+psycopg2://crash@/cmdev'
      sql_tracing:  false

    local_dev3:
      connect_str:  'postgresql+psycopg2://crash@/cmdev3'
      sql_tracing:  false

    server_dev:
      connect_str:  'postgresql+psycopg2://cmir:cmir@caladan/cmdev'
      sql_tracing:  false

    server_dev3:
      connect_str:  'postgresql+psycopg2://cmir:cmir@caladan/cmdev3'
      sql_tracing:  false

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_test:
      connect_str:  'postgresql+psycopg2://crash@/cmtest'
      sql_tracing:  false

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_prod:
      connect_str:  'postgresql+psycopg2://crash@/cmprod'

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_prod3:
      connect_str:  'postgresql+psycopg2://crash@/cmprod3'

  environment:
    'delta:/home/crash/dev/cmdev':
      envname:     'delta_dev'
      database:    'local_dev'

    'delta:/home/crash/dev/cmdev3':
      envname:     'delta_dev3'
      database:    'server_dev3'
      #html_parser: 'html5lib'  -- adds tbody, doesn't handle non-closing <a>
      #html_parser: 'lxml'      -- freaks out with C24/playlists/2018-09-17.html

    'delta:/local/test/cmtest':
      envname:     'delta_test'
      database:    'local_test'

    'caladan:/local/test/cmtest':
      envname:     'caladan_test'
      database:    'local_test'

    'caladan:/local/prod/cmprod':
      envname:     'caladan_prod'
      database:    'local_prod'

    'caladan:/local/prod/cmprod3':
      envname:     'caladan_prod3'
      database:    'local_prod3'
