---
default:
  station_base:
    http_headers:   {'User-Agent': 'Mozilla/5.0'}
    fetch_interval: 1.0

  stations:
    BEET:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/55913d0c8fa46b530f88384b/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '55913d0c8fa46b530f88384b'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2015-06-29'
      parser_cls:   'ParserWWFM'
      synd_level:   15

    C24A:
      sample_url:   'https://www.classical24.org/api/playlist/2019-01-13'
      url_fmt:      'https://www.classical24.org/api/playlist/<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'json'
      epoch:        '2014-09-15'
      parser_cls:   'Parser'
      synd_level:   100

    C24B:
      sample_url:   'https://www.yourclassical.org/_next/data/yrnoxhNmCTzrBhQRurpi-/schedule/classical-24/2019-09-16.json'
      url_fmt:      'https://www.yourclassical.org/_next/data/<WIDGETKEY>/schedule/classical-24/<DATE_STR>.json'
      #widgetkey:    'yrnoxhNmCTzrBhQRurpi-'  # 2202-02
      widgetkey:    'lgYVyvcmAcb1eiMXe5h4Z'  # 2202-03
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'json'
      epoch:        '2014-09-15'
      parser_cls:   'ParserC24B'
      synd_level:   100

    CPR:
      sample_url:   'http://playlist.cprnetwork.org/api/playlistCL/selectDate:MjAxOC0wOS0xMg=='
      url_fmt:      'http://playlist.cprnetwork.org/api/playlistCL/selectDate:<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      date_func:    'base64encode'
      timezone:     'America/Denver'
      playlist_ext: 'json'
      parser_cls:   'Parser'

    HPR:
      sample_url:   'https://www.houstonpublicmedia.org/classical/schedule/2018/09/12/'
      url_fmt:      'https://www.houstonpublicmedia.org/classical/schedule/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2013-05-01'
      parser_cls:   'Parser'

    IPR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/518277f7e1c83ecee40d8eb1/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '518277f7e1c83ecee40d8eb1'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'json'
      epoch:        '2013-07-01'
      parser_cls:   'ParserWWFM'
      synd_level:   90

    KDFC:
      sample_url:   'https://www.kdfc.com/playlist/2018/09/07/'
      sample_url2:  'https://www.kdfc.com/playlist/2018/09/06/?_pjax=%23main'
      url_fmt:      'https://www.kdfc.com/playlist/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2013-06-30'
      parser_cls:   'Parser'

    KING:
      sample_url:   'https://www.king.org/music-schedule/?npDate=01012018'
      url_fmt:      'https://www.king.org/music-schedule/?npDate=<DATE_STR>'
      date_fmt:     '%m%d%Y'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2014-01-01'
      parser_cls:   'Parser'

    KQAC:
      sample_url:   'https://daisy.allclassical.org/api/playlist/date/2018-09-12/'
      url_fmt:      'https://daisy.allclassical.org/api/playlist/date/<DATE_STR>/'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'json'
      epoch:        '2015-05-01'
      parser_cls:   'Parser'

    KUSC:
      sample_url:   'https://www.kusc.org/playlist/2018/09/05/'
      sample_url2:  'https://www.kusc.org/playlist/2018/09/05/?_pjax=%23main'
      url_fmt:      'https://www.kusc.org/playlist/<DATE_STR>/'
      date_fmt:     '%Y/%m/%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'html'
      epoch:        '2013-01-06'
      parser_cls:   'Parser'

    MPR:
      sample_url:   'https://www.classicalmpr.org/playlist/classical-mpr/2018-09-12'
      url_fmt:      'https://www.classicalmpr.org/playlist/classical-mpr/<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2006-01-27'
      parser_cls:   'ParserMPR'
      synd_level:   80

    MPR2:
      sample_url:   'https://www.yourclassical.org/_next/data/yrnoxhNmCTzrBhQRurpi-/schedule/classical-mpr/2022-02-22.json'
      url_fmt:      'https://www.yourclassical.org/_next/data/<WIDGETKEY>/schedule/classical-mpr/<DATE_STR>.json'
      #widgetkey:    'yrnoxhNmCTzrBhQRurpi-'  # 2202-02
      widgetkey:    'lgYVyvcmAcb1eiMXe5h4Z'  # 2202-03
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'json'
      epoch:        '2006-01-27'
      parser_cls:   'ParserC24B'
      synd_level:   80

    NWPR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/5187c750e1c8c870fd6d9fbc/day?date=2019-05-01&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '5187c750e1c8c870fd6d9fbc'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Los_Angeles'
      playlist_ext: 'json'
      epoch:        '2013-12-16'
      parser_cls:   'ParserWWFM'
      synd_level:   35

    VPR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/518028fee1c810b152ff9766/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '518028fee1c810b152ff9766'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-12-15'
      parser_cls:   'ParserWWFM'
      synd_level:   50

    WBJC:
      sample_url:   'http://www.wbjc.com/2018/playlists/playlist-sep-15-18/'
      url_fmt:      'http://www.wbjc.com/<DATE_STR2>/playlists/playlist-<DATE_STR>/'
      date_fmt:     '%b-%d-%y'
      date_fmt2:    '%Y'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-01-01'
      parser_cls:   'Parser'

    WBAA:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/5187ee3ce1c868cbf096f78a/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '5187ee3ce1c868cbf096f78a'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-04-26'
      parser_cls:   'ParserWWFM'
      synd_level:   39

    WCPE:
      # Note: date in URL is the Monday of the week (needs to be handled in date_func)
      sample_url:   'https://theclassicalstation.org/music/archive/2018-09-17/tuesday.shtml'
      # the following works for the prior 7 days (counting current day)
      sample_url2:  'https://theclassicalstation.org/music/friday.shtml'
      urls:
        - cond:         '-6'
          url_fmt:      'https://theclassicalstation.org/music/<DATE_STR>.shtml'
          date_fmt:     '%A'
          date_meth:    'lower'
        - cond:         'default'
          url_fmt:      'https://theclassicalstation.org/music/archive/<DATE_STR>.shtml'
          date_fmt:     '%Y-%m-%d/%A'
          date_func:    'wcpe_special'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2011-08-15'
      parser_cls:   'Parser'

    WCRB:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53877c98e1c80a130decb6c8/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53877c98e1c80a130decb6c8'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-07-01'
      parser_cls:   'ParserWWFM'
      synd_level:   30

    WDAV:
      sample_url:   'https://app.wdav.org/app-playlist/index.cfm?thisday=2017-09-05'
      url_fmt:      'https://app.wdav.org/app-playlist/index.cfm?thisday=<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2006-03-06'
      parser_cls:   'Parser'

    WETA:
      sample_url:   'https://weta.org/fm/playlists?date=2018-09-08'
      url_fmt:      'https://weta.org/fm/playlists?date=<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-01-01'
      parser_cls:   'Parser'

    WFMT:
      sample_url:   'https://www.wfmt.com/schedule/?pldate=08/05/2018'
      url_fmt:      'https://www.wfmt.com/schedule/?pldate=<DATE_STR>'
      date_fmt:     '%m/%d/%Y'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2018-07-01'
      parser_cls:   'Parser'

    WIAA:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/52615808e1c8fbf0ddcb3d04/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '52615808e1c8fbf0ddcb3d04'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-11-11'
      parser_cls:   'ParserWWFM'
      synd_level:   40

    WKAR:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/5187f425e1c860c702f81c62/day?date=2019-05-01&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '5187f425e1c860c702f81c62'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-03-10'
      parser_cls:   'ParserWWFM'
      synd_level:   55

    WKAR2:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/5187f3e0e1c8212f45d325a7/day?date=2019-05-01&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '5187f3e0e1c8212f45d325a7'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-12-02'
      parser_cls:   'ParserWWFM'
      synd_level:   54

    WMHT:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51892578e1c81d34d1474a5d/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51892578e1c81d34d1474a5d'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-06-03'
      parser_cls:   'ParserWWFM'
      synd_level:   60

    WNED:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51929c5ce1c8c39684eeee82/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51929c5ce1c8c39684eeee82'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-12-24'
      parser_cls:   'ParserWWFM'
      synd_level:   20

    WOSU2:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/5182cf51e1c86c00f5732300/day?date=2019-05-01&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '5182cf51e1c86c00f5732300'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-07-31'
      parser_cls:   'ParserWWFM'
      synd_level:   25

    WPR:
      sample_url:   'https://wpr.net/guts/playlists/build_allclassicalcalendars_iframe.cfm?date=2019-01-15'
      url_fmt:      'https://wpr.net/guts/playlists/build_allclassicalcalendars_iframe.cfm?date=<DATE_STR>'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/Chicago'
      playlist_ext: 'html'
      epoch:        '2010-05-12'
      parser_cls:   'Parser'

    WQED:
      sample_url:   'https://www.wqed.org/fm/playlist?day=09/05/2018'
      url_fmt:      'https://www.wqed.org/fm/playlist?day=<DATE_STR>'
      date_fmt:     '%m/%d/%Y'
      timezone:     'America/New_York'
      playlist_ext: 'html'
      epoch:        '2018-07-10'
      parser_cls:   'Parser'

    WQXR:
      sample_url:   'https://www.wqxr.org/api/schedule_playlist_json/wqxr/2017/sep/01/'
      url_fmt:      'https://www.wqxr.org/api/schedule_playlist_json/wqxr/<DATE_STR>/'
      date_fmt:     '%Y/%b/%d'
      date_meth:    'lower'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      parser_cls:   'Parser'

    WRTI:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53c7dbe1e1c8b9c77b4b9b6e/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53c7dbe1e1c8b9c77b4b9b6e'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2014-05-01'
      parser_cls:   'ParserWWFM'
      synd_level:   10

    WSHU:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51c0a882e1c8a56086657e1e/day?format=json&date=2020-11-15&times=true'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51c0a882e1c8a56086657e1e'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-05-01'
      parser_cls:   'ParserWWFM'
      synd_level:   70

    WWFM:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/53a98e36e1c80647e855fc88/day?date=2018-09-06&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '53a98e36e1c80647e855fc88'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      playlist_ext: 'json'
      epoch:        '2013-11-11'
      playlist_min: 5000
      parser_cls:   'ParserWWFM'
      synd_level:   70

    WXXI:
      sample_url:   'https://api.composer.nprstations.org/v1/widget/51ad047be1c860e313636032/day?date=2018-10-10&format=json'
      url_fmt:      'https://api.composer.nprstations.org/v1/widget/<WIDGETKEY>/day?date=<DATE_STR>&format=json'
      widgetkey:    '51ad047be1c860e313636032'
      date_fmt:     '%Y-%m-%d'
      timezone:     'America/New_York'
      epoch:        '2014-06-30'
      playlist_ext: 'json'
      parser_cls:   'ParserWWFM'
      synd_level:   75

  refdata_base:
    http_headers:   {'User-Agent': 'Mozilla/5.0'}
    catdata_ext:   'html'
    fetch_interval: 1.0

  refdata:
    arkivmusic:
      # LATER: abstract to 'browse_by'
      url_fmt:      'http://www.arkivmusic.com/classical/NameList?alpha=<STARTS_WITH>&role_wanted=<ROLE>'
      charset:      'iso-8859-1'

      categories:
        composers:
          role:     1
        performers:
          role:     2
        conductors:
          role:     3
        ensembles:
          role:     4

  database:
    local_dev:
      connect_str:  'postgresql+psycopg2://crash@/cmdev'
      sql_tracing:  false

    local_dev3:
      connect_str:  'postgresql+psycopg2://crash@/cmdev3'
      sql_tracing:  false

    server_dev:
      connect_str:  'postgresql+psycopg2://cmir:cmir@caladan/cmdev'
      sql_tracing:  false

    server_dev3:
      connect_str:  'postgresql+psycopg2://cmir:cmir@caladan/cmdev3'
      sql_tracing:  false

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_test:
      connect_str:  'postgresql+psycopg2://crash@/cmtest'
      sql_tracing:  false

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_prod:
      connect_str:  'postgresql+psycopg2://crash@/cmprod'

    # CAREFUL: this is local to the environment being run, thus reusable across machines
    local_prod3:
      connect_str:  'postgresql+psycopg2://crash@/cmprod3'

  environment:
    'arrakis:/home/crash/dev/cmdev':
      envname:     'arrakis_dev'
      database:    'local_dev'

    'arrakis:/home/crash/dev/cmdev3':
      envname:     'arrakis_dev3'
      database:    'local_dev3'
      #html_parser: 'html5lib'  -- adds tbody, doesn't handle non-closing <a>
      #html_parser: 'lxml'      -- freaks out with C24/playlists/2018-09-17.html

    'arrakis:/local/test/cmtest':
      envname:     'arrakis_test'
      database:    'local_test'

    'caladan:/local/test/cmtest':
      envname:     'caladan_test'
      database:    'local_test'

    'caladan:/local/prod/cmprod':
      envname:     'caladan_prod'
      database:    'local_prod'

    'caladan:/local/prod/cmprod3':
      envname:     'caladan_prod3'
      database:    'local_prod3'
